### ISSUE TITLE
(Request) Can you share your trainneddata?

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [Chaarangan/tamizhinet-corpus#1]
I am currently working on a python script surrounding the Tesseract OCR, and I am in need of good trainneddata for Tamil. Will it be possible for you to share yours?

Thank you.

**Comment by Chaarangan** [comment]
Hi,
Thanks for reaching out to me. You can find the traineddata here: https://github.com/Chaarangan/aaivu-tamizhi-net-OCR/tree/master/src/traineddata

Thanks,
Charangan
